# Generated by Django 5.0.6 on 2024-06-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_applicationrecords_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrecords",
            name="invoice",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
