# Generated by Django 5.0.6 on 2024-05-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="requirements",
            field=models.TextField(default="sd"),
            preserve_default=False,
        ),
    ]
