# Generated by Django 5.0.6 on 2024-05-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_applicationrecords_amount_applicationfiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrecords",
            name="filesUploaded",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
