# Generated by Django 5.0.6 on 2024-05-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_prices_delete_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrecords",
            name="transactioncode",
            field=models.CharField(default="xx", max_length=100),
            preserve_default=False,
        ),
    ]
