# Generated by Django 5.0.6 on 2024-05-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_applicationrecords_transactioncode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrecords",
            name="paymentStatus",
            field=models.TextField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Unpaid", "Unpaid"),
                    ("Declined", "Declined"),
                ],
                max_length=30,
            ),
        ),
    ]
