# Generated by Django 5.0.6 on 2024-05-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_applicationrecords_paymentstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrecords",
            name="resolution",
            field=models.TextField(
                choices=[
                    ("Closed", "Closed"),
                    ("Pending", "Pending"),
                    ("Declined", "Declined"),
                ],
                default="Pending",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
