# Generated by Django 5.0.6 on 2024-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_applicationrecords_resolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationrecords",
            name="resolution",
            field=models.TextField(
                choices=[("New", "New"), ("Queued", "Queued"), ("Closed", "Closed")],
                max_length=100,
            ),
        ),
    ]
