# Generated by Django 5.0.6 on 2024-06-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_companyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationrecords",
            name="remarks",
            field=models.TextField(null=True),
        ),
    ]
