# Generated by Django 5.0.6 on 2024-06-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_applicationrecords_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="accountno",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="paybill",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="tillno",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
