# Generated by Django 5.1.4 on 2025-01-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Normal User"),
                    ("superAdmin", "Super Admin"),
                    ("admin", "County Admin"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
